import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service - Ubenie",
  description:
    "Terms of Service for Ubenie - AI-powered content generation platform for SEO-optimized blog posts.",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white py-16">
      <div className="container mx-auto px-4 max-w-4xl">
        <Link
          href="/"
          className="text-blue-600 hover:text-blue-800 mb-8 inline-block"
        >
          ← Back to Home
        </Link>

        <h1 className="text-4xl md:text-5xl font-bold text-gray-900 mb-4">
          Terms of Service
        </h1>
        <p className="text-gray-600 mb-12">Last Updated: October 10, 2025</p>

        <div className="prose prose-lg max-w-none space-y-8">
          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">
              1. Agreement to Terms
            </h2>
            <p className="text-gray-700 leading-relaxed">
              By accessing or using Ubenie (&quot;Service&quot;), you agree to
              be bound by these Terms of Service. If you disagree with any part
              of these terms, you may not access the Service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">
              2. Description of Service
            </h2>
            <p className="text-gray-700 leading-relaxed">
              Ubenie is an AI-powered content generation platform that helps
              businesses create SEO-optimized blog posts. The Service uses
              artificial intelligence to research keywords, generate content,
              and assist with content strategy.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">
              3. User Accounts
            </h2>
            <p className="text-gray-700 leading-relaxed mb-4">
              When you create an account with us, you must provide accurate,
              complete, and current information. You are responsible for:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-gray-700">
              <li>Maintaining the security of your account and password</li>
              <li>All activities that occur under your account</li>
              <li>Notifying us immediately of any unauthorized use</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">
              4. Acceptable Use
            </h2>
            <p className="text-gray-700 leading-relaxed mb-4">
              You agree not to use the Service to:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-gray-700">
              <li>
                Generate content that is illegal, harmful, or violates any laws
              </li>
              <li>Create misleading, false, or deceptive content</li>
              <li>Infringe upon intellectual property rights of others</li>
              <li>
                Attempt to gain unauthorized access to our systems or networks
              </li>
              <li>
                Use the Service to spam or send unsolicited communications
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">
              5. Content Ownership and Rights
            </h2>
            <p className="text-gray-700 leading-relaxed">
              You retain all rights to the content you create using Ubenie. We
              do not claim ownership of your generated content. However, you
              grant us a limited license to use your content for the purposes of
              providing and improving the Service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">
              6. AI-Generated Content
            </h2>
            <p className="text-gray-700 leading-relaxed">
              Content generated by our AI is provided as-is. You are responsible
              for reviewing, editing, and ensuring the accuracy and
              appropriateness of all AI-generated content before publishing. We
              do not guarantee the accuracy, completeness, or suitability of
              AI-generated content for any particular purpose.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">
              7. Payment and Subscription
            </h2>
            <p className="text-gray-700 leading-relaxed mb-4">
              If you subscribe to a paid plan:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-gray-700">
              <li>
                Subscription fees are billed in advance on a recurring basis
              </li>
              <li>You can cancel your subscription at any time</li>
              <li>Refunds are provided according to our refund policy</li>
              <li>We reserve the right to change pricing with notice</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">
              8. Service Availability
            </h2>
            <p className="text-gray-700 leading-relaxed">
              We strive to provide reliable service but do not guarantee
              uninterrupted access. We may modify, suspend, or discontinue any
              part of the Service at any time with or without notice.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">
              9. Limitation of Liability
            </h2>
            <p className="text-gray-700 leading-relaxed">
              Ubenie and its affiliates shall not be liable for any indirect,
              incidental, special, consequential, or punitive damages resulting
              from your use or inability to use the Service. Our total liability
              shall not exceed the amount you paid us in the past 12 months.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">
              10. Indemnification
            </h2>
            <p className="text-gray-700 leading-relaxed">
              You agree to indemnify and hold harmless Ubenie from any claims,
              damages, or expenses arising from your use of the Service, your
              violation of these Terms, or your violation of any rights of
              another.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">
              11. Termination
            </h2>
            <p className="text-gray-700 leading-relaxed">
              We may terminate or suspend your account immediately, without
              prior notice, for any reason, including breach of these Terms.
              Upon termination, your right to use the Service will immediately
              cease.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">
              12. Changes to Terms
            </h2>
            <p className="text-gray-700 leading-relaxed">
              We reserve the right to modify these Terms at any time. We will
              notify you of any changes by posting the new Terms on this page
              and updating the &quot;Last Updated&quot; date. Your continued use
              of the Service after changes constitutes acceptance of the new
              Terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">
              13. Governing Law
            </h2>
            <p className="text-gray-700 leading-relaxed">
              These Terms shall be governed by and construed in accordance with
              the laws of Serbia, without regard to its conflict of law
              provisions.
            </p>
          </section>

          {/* <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">
              14. Contact Us
            </h2>
            <p className="text-gray-700 leading-relaxed">
              If you have any questions about these Terms, please contact us at:
            </p>
            <p className="text-gray-700 mt-4">
              <strong>Email:</strong> support@ubenie.com
              <br />
              <strong>Location:</strong> Belgrade, Serbia
            </p>
          </section> */}
        </div>

        <div className="mt-12 pt-8 border-t border-gray-200">
          <Link
            href="/"
            className="text-blue-600 hover:text-blue-800 font-semibold"
          >
            ← Back to Home
          </Link>
        </div>
      </div>
    </div>
  );
}
